//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace cnrl.guarani {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DatosAlumnosBecasPortBinding", Namespace="http://webService.unlm/")]
    public partial class DatosAlumnosBecas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaDatosAlumnosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaDatosAlumnosEFCOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaDatosAlumnosG3OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DatosAlumnosBecas() {
            this.Url = global::cnrl.Properties.Settings.Default.cnrl_guarani_DatosAlumnosBecas;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaDatosAlumnosCompletedEventHandler consultaDatosAlumnosCompleted;
        
        /// <remarks/>
        public event consultaDatosAlumnosEFCCompletedEventHandler consultaDatosAlumnosEFCCompleted;
        
        /// <remarks/>
        public event consultaDatosAlumnosG3CompletedEventHandler consultaDatosAlumnosG3Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webService.unlm/", ResponseNamespace="http://webService.unlm/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultaDatosAlumnos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nro_documento) {
            object[] results = this.Invoke("consultaDatosAlumnos", new object[] {
                        nro_documento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaDatosAlumnosAsync(string nro_documento) {
            this.consultaDatosAlumnosAsync(nro_documento, null);
        }
        
        /// <remarks/>
        public void consultaDatosAlumnosAsync(string nro_documento, object userState) {
            if ((this.consultaDatosAlumnosOperationCompleted == null)) {
                this.consultaDatosAlumnosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaDatosAlumnosOperationCompleted);
            }
            this.InvokeAsync("consultaDatosAlumnos", new object[] {
                        nro_documento}, this.consultaDatosAlumnosOperationCompleted, userState);
        }
        
        private void OnconsultaDatosAlumnosOperationCompleted(object arg) {
            if ((this.consultaDatosAlumnosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaDatosAlumnosCompleted(this, new consultaDatosAlumnosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webService.unlm/", ResponseNamespace="http://webService.unlm/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultaDatosAlumnosEFC([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nro_documento) {
            object[] results = this.Invoke("consultaDatosAlumnosEFC", new object[] {
                        nro_documento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaDatosAlumnosEFCAsync(string nro_documento) {
            this.consultaDatosAlumnosEFCAsync(nro_documento, null);
        }
        
        /// <remarks/>
        public void consultaDatosAlumnosEFCAsync(string nro_documento, object userState) {
            if ((this.consultaDatosAlumnosEFCOperationCompleted == null)) {
                this.consultaDatosAlumnosEFCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaDatosAlumnosEFCOperationCompleted);
            }
            this.InvokeAsync("consultaDatosAlumnosEFC", new object[] {
                        nro_documento}, this.consultaDatosAlumnosEFCOperationCompleted, userState);
        }
        
        private void OnconsultaDatosAlumnosEFCOperationCompleted(object arg) {
            if ((this.consultaDatosAlumnosEFCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaDatosAlumnosEFCCompleted(this, new consultaDatosAlumnosEFCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webService.unlm/", ResponseNamespace="http://webService.unlm/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultaDatosAlumnosG3([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string nro_documento) {
            object[] results = this.Invoke("consultaDatosAlumnosG3", new object[] {
                        nro_documento});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaDatosAlumnosG3Async(string nro_documento) {
            this.consultaDatosAlumnosG3Async(nro_documento, null);
        }
        
        /// <remarks/>
        public void consultaDatosAlumnosG3Async(string nro_documento, object userState) {
            if ((this.consultaDatosAlumnosG3OperationCompleted == null)) {
                this.consultaDatosAlumnosG3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaDatosAlumnosG3OperationCompleted);
            }
            this.InvokeAsync("consultaDatosAlumnosG3", new object[] {
                        nro_documento}, this.consultaDatosAlumnosG3OperationCompleted, userState);
        }
        
        private void OnconsultaDatosAlumnosG3OperationCompleted(object arg) {
            if ((this.consultaDatosAlumnosG3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaDatosAlumnosG3Completed(this, new consultaDatosAlumnosG3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void consultaDatosAlumnosCompletedEventHandler(object sender, consultaDatosAlumnosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaDatosAlumnosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaDatosAlumnosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void consultaDatosAlumnosEFCCompletedEventHandler(object sender, consultaDatosAlumnosEFCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaDatosAlumnosEFCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaDatosAlumnosEFCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void consultaDatosAlumnosG3CompletedEventHandler(object sender, consultaDatosAlumnosG3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaDatosAlumnosG3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaDatosAlumnosG3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591