//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cursa()
        {
            this.asistencia = new HashSet<asistencia>();
            this.Encuesta = new HashSet<Encuesta>();
        }
    
        public int oferta { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public bool aprobo { get; set; }
        public string nota { get; set; }
        public string observacion { get; set; }
        public string alumno { get; set; }
        public int codigo { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> cantidadCuotas { get; set; }
        public bool RequierePreInscripcion { get; set; }
        public Nullable<int> baja { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
        public Nullable<double> porcentajeBeca { get; set; }
        public string DescripcionBaja { get; set; }
        public Nullable<int> EstadoAntBaja { get; set; }
        public Nullable<int> resultadoCursada { get; set; }
        public Nullable<bool> ValidarNota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<asistencia> asistencia { get; set; }
        public virtual EstadoCursa EstadoCursa { get; set; }
        public virtual motivoBaja motivoBaja { get; set; }
        public virtual ResultadoCursa ResultadoCursa { get; set; }
        public virtual oferta oferta1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encuesta> Encuesta { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
