//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public curso()
        {
            this.nivelacion = new HashSet<nivelacion>();
            this.curso1 = new HashSet<curso>();
            this.curso2 = new HashSet<curso>();
            this.oferta = new HashSet<oferta>();
            this.oferta1 = new HashSet<oferta>();
        }
    
        public int codigo { get; set; }
        public string descripcion { get; set; }
        public int horasSemanales { get; set; }
        public int concepto { get; set; }
        public int tipoCurso { get; set; }
        public int nivel { get; set; }
        public string extraInfo { get; set; }
        public Nullable<int> codCurso { get; set; }
        public bool RequierePreInscripcion { get; set; }
        public string documentacion { get; set; }
        public Nullable<System.DateTime> fechaDocumentacion { get; set; }
        public Nullable<System.TimeSpan> horaDocumentacion { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
        public string AdminCurso { get; set; }
        public string AdminCurso2 { get; set; }
        public string AdminCurso3 { get; set; }
        public string AdminCurso4 { get; set; }
        public bool gratuito { get; set; }
    
        public virtual precio precio { get; set; }
        public virtual tipocurso tipocurso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nivelacion> nivelacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curso> curso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curso> curso2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferta> oferta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferta> oferta1 { get; set; }
    }
}
