//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        public string id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idRespuesta { get; set; }
        public Nullable<int> idCursa { get; set; }
    
        public virtual RespuestasEncuesta RespuestasEncuesta { get; set; }
        public virtual cursa cursa { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
