//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl
{
    using System;
    using System.Collections.Generic;
    
    public partial class periodolectivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public periodolectivo()
        {
            this.oferta = new HashSet<oferta>();
            this.oferta1 = new HashSet<oferta>();
        }
    
        public int anio { get; set; }
        public int periodo { get; set; }
        public System.DateTime desdeFecha { get; set; }
        public System.DateTime hastaFecha { get; set; }
        public int codigo { get; set; }
        public int tipoCurso { get; set; }
        public Nullable<System.DateTime> fechaInscripcionDesde { get; set; }
        public Nullable<System.DateTime> fechaInscripcionHasta { get; set; }
        public Nullable<System.DateTime> fechaPrimeraCuota { get; set; }
        public Nullable<System.TimeSpan> periodoHoraDesde { get; set; }
        public Nullable<System.TimeSpan> periodoHoraHasta { get; set; }
        public Nullable<System.TimeSpan> inscripcionHoraDesde { get; set; }
        public Nullable<System.TimeSpan> inscripcionHoraHasta { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
    
        public virtual tipocurso tipocurso1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferta> oferta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferta> oferta1 { get; set; }
    }
}
