//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl
{
    using System;
    using System.Collections.Generic;
    
    public partial class permiso
    {
        public int codigo { get; set; }
        public Nullable<int> pagina { get; set; }
        public string tipoUsuario { get; set; }
        public string nombre { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
    }
}
