//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl
{
    using System;
    using System.Collections.Generic;
    
    public partial class precio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public precio()
        {
            this.curso = new HashSet<curso>();
        }
    
        public int codigo { get; set; }
        public double alumno { get; set; }
        public double noalumno { get; set; }
        public double empleado { get; set; }
        public Nullable<double> descuentoBandaNegativa { get; set; }
        public string descripcion { get; set; }
        public double mayorDe60 { get; set; }
        public Nullable<double> descuentoUnaCuota { get; set; }
        public Nullable<int> diasSegundoVencimiento { get; set; }
        public Nullable<double> recargoSegundoVencimiento { get; set; }
        public Nullable<int> concepto { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserCreated { get; set; }
        public string UserModified { get; set; }
        public bool gratuito { get; set; }
        public Nullable<double> graduado { get; set; }
        public Nullable<int> sector { get; set; }
        public Nullable<double> descuentoBandaNegativaNoAlumno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curso> curso { get; set; }
        public virtual Sector Sector1 { get; set; }
    }
}
