//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("cnrl.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursos de Extensión Universitaria.
        /// </summary>
        public static string AppTitulo {
            get {
                return ResourceManager.GetString("AppTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string BtnAgregar {
            get {
                return ResourceManager.GetString("BtnAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string BtnBorrar {
            get {
                return ResourceManager.GetString("BtnBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string BtnBuscar {
            get {
                return ResourceManager.GetString("BtnBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string BtnCancelar {
            get {
                return ResourceManager.GetString("BtnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string BtnCerrar {
            get {
                return ResourceManager.GetString("BtnCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        public static string BtnDocumentos {
            get {
                return ResourceManager.GetString("BtnDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string BtnEditar {
            get {
                return ResourceManager.GetString("BtnEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string BtnGuardar {
            get {
                return ResourceManager.GetString("BtnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitar/Deshabilitar.
        /// </summary>
        public static string BtnHabilitar {
            get {
                return ResourceManager.GetString("BtnHabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inscribir.
        /// </summary>
        public static string BtnInscribir {
            get {
                return ResourceManager.GetString("BtnInscribir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Email.
        /// </summary>
        public static string BtnMail {
            get {
                return ResourceManager.GetString("BtnMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva.
        /// </summary>
        public static string BtnNueva {
            get {
                return ResourceManager.GetString("BtnNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string BtnNuevo {
            get {
                return ResourceManager.GetString("BtnNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pre Cargar Nota.
        /// </summary>
        public static string BtnPrecargarNota {
            get {
                return ResourceManager.GetString("BtnPrecargarNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string BtnSeleccionar {
            get {
                return ResourceManager.GetString("BtnSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        public static string BtnVer {
            get {
                return ResourceManager.GetString("BtnVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver Ficha.
        /// </summary>
        public static string BtnVerFicha {
            get {
                return ResourceManager.GetString("BtnVerFicha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string ColActivo {
            get {
                return ResourceManager.GetString("ColActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Act.
        /// </summary>
        public static string ColActivoCorto {
            get {
                return ResourceManager.GetString("ColActivoCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alumno.
        /// </summary>
        public static string ColAlumno {
            get {
                return ResourceManager.GetString("ColAlumno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo.
        /// </summary>
        public static string ColCampo {
            get {
                return ResourceManager.GetString("ColCampo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos.
        /// </summary>
        public static string ColCampos {
            get {
                return ResourceManager.GetString("ColCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel de Complejidad.
        /// </summary>
        public static string ColComplejidad {
            get {
                return ResourceManager.GetString("ColComplejidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion del Nivel de Complejidad.
        /// </summary>
        public static string ColComplejidadDescripcion {
            get {
                return ResourceManager.GetString("ColComplejidadDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Concepto.
        /// </summary>
        public static string ColConcepto {
            get {
                return ResourceManager.GetString("ColConcepto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativa.
        /// </summary>
        public static string ColCorrelativa {
            get {
                return ResourceManager.GetString("ColCorrelativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a C.P..
        /// </summary>
        public static string ColCp {
            get {
                return ResourceManager.GetString("ColCp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        public static string ColCpLargo {
            get {
                return ResourceManager.GetString("ColCpLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota.
        /// </summary>
        public static string ColCuota {
            get {
                return ResourceManager.GetString("ColCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Curso.
        /// </summary>
        public static string ColCurso {
            get {
                return ResourceManager.GetString("ColCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string ColDescripcion {
            get {
                return ResourceManager.GetString("ColDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción abreviada.
        /// </summary>
        public static string ColDescripcionCorta {
            get {
                return ResourceManager.GetString("ColDescripcionCorta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Día.
        /// </summary>
        public static string ColDia {
            get {
                return ResourceManager.GetString("ColDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Docente.
        /// </summary>
        public static string ColDocente {
            get {
                return ResourceManager.GetString("ColDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string ColDocumento {
            get {
                return ResourceManager.GetString("ColDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string ColDomicilio {
            get {
                return ResourceManager.GetString("ColDomicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string ColEmail {
            get {
                return ResourceManager.GetString("ColEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especialidad.
        /// </summary>
        public static string ColEspecialidad {
            get {
                return ResourceManager.GetString("ColEspecialidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string ColEstado {
            get {
                return ResourceManager.GetString("ColEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Baja.
        /// </summary>
        public static string ColFechaBaja {
            get {
                return ResourceManager.GetString("ColFechaBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Pago.
        /// </summary>
        public static string ColFechaPago {
            get {
                return ResourceManager.GetString("ColFechaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primer Vencimiento.
        /// </summary>
        public static string ColFechaVto {
            get {
                return ResourceManager.GetString("ColFechaVto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Segundo Vencimiento.
        /// </summary>
        public static string ColFechaVto2 {
            get {
                return ResourceManager.GetString("ColFechaVto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string ColId {
            get {
                return ResourceManager.GetString("ColId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe 1er Vencimiento.
        /// </summary>
        public static string ColImporte {
            get {
                return ResourceManager.GetString("ColImporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importe 2do Vencimiento.
        /// </summary>
        public static string ColImporte2 {
            get {
                return ResourceManager.GetString("ColImporte2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver registros inactivos.
        /// </summary>
        public static string ColInactivos {
            get {
                return ResourceManager.GetString("ColInactivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instituto.
        /// </summary>
        public static string ColInstituto {
            get {
                return ResourceManager.GetString("ColInstituto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Institutos.
        /// </summary>
        public static string ColInstitutos {
            get {
                return ResourceManager.GetString("ColInstitutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jurisdicción.
        /// </summary>
        public static string ColJurisdiccion {
            get {
                return ResourceManager.GetString("ColJurisdiccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JURISDICCIONAL.
        /// </summary>
        public static string ColJurisdiccional {
            get {
                return ResourceManager.GetString("ColJurisdiccional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOCAL.
        /// </summary>
        public static string ColLocal {
            get {
                return ResourceManager.GetString("ColLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        public static string ColLocalidad {
            get {
                return ResourceManager.GetString("ColLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NACIONAL.
        /// </summary>
        public static string ColNacional {
            get {
                return ResourceManager.GetString("ColNacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string ColNivel {
            get {
                return ResourceManager.GetString("ColNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string ColNivelLargo {
            get {
                return ResourceManager.GetString("ColNivelLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodo.
        /// </summary>
        public static string ColNodo {
            get {
                return ResourceManager.GetString("ColNodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodos.
        /// </summary>
        public static string ColNodos {
            get {
                return ResourceManager.GetString("ColNodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string ColNombre {
            get {
                return ResourceManager.GetString("ColNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        public static string ColNotas {
            get {
                return ResourceManager.GetString("ColNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nº Cuota.
        /// </summary>
        public static string ColNroCuota {
            get {
                return ResourceManager.GetString("ColNroCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oferta.
        /// </summary>
        public static string ColOferta {
            get {
                return ResourceManager.GetString("ColOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Orden.
        /// </summary>
        public static string ColOrden {
            get {
                return ResourceManager.GetString("ColOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo Lectivo.
        /// </summary>
        public static string ColPeriodo {
            get {
                return ResourceManager.GetString("ColPeriodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona.
        /// </summary>
        public static string ColPersona {
            get {
                return ResourceManager.GetString("ColPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        public static string ColRed {
            get {
                return ResourceManager.GetString("ColRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes.
        /// </summary>
        public static string ColRedes {
            get {
                return ResourceManager.GetString("ColRedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es Referente?.
        /// </summary>
        public static string ColReferente {
            get {
                return ResourceManager.GetString("ColReferente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinador Jurisdiccional.
        /// </summary>
        public static string ColReferenteJurisdiccional {
            get {
                return ResourceManager.GetString("ColReferenteJurisdiccional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Región Sanitaria.
        /// </summary>
        public static string ColRegion {
            get {
                return ResourceManager.GetString("ColRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regiones.
        /// </summary>
        public static string ColRegiones {
            get {
                return ResourceManager.GetString("ColRegiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        public static string ColResponsable {
            get {
                return ResourceManager.GetString("ColResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable de Instituto.
        /// </summary>
        public static string ColResponsableIns {
            get {
                return ResourceManager.GetString("ColResponsableIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinador de Jurisdicción.
        /// </summary>
        public static string ColResponsableJur {
            get {
                return ResourceManager.GetString("ColResponsableJur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable del Nodo.
        /// </summary>
        public static string ColResponsableNodo {
            get {
                return ResourceManager.GetString("ColResponsableNodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinador de Red.
        /// </summary>
        public static string ColResponsableRedJur {
            get {
                return ResourceManager.GetString("ColResponsableRedJur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordinador de Red.
        /// </summary>
        public static string ColResponsableRedNac {
            get {
                return ResourceManager.GetString("ColResponsableRedNac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsables.
        /// </summary>
        public static string ColResponsables {
            get {
                return ResourceManager.GetString("ColResponsables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resp..
        /// </summary>
        public static string ColResponsablesCorto {
            get {
                return ResourceManager.GetString("ColResponsablesCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable de Servicio.
        /// </summary>
        public static string ColResponsableSer {
            get {
                return ResourceManager.GetString("ColResponsableSer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string ColRol {
            get {
                return ResourceManager.GetString("ColRol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sede.
        /// </summary>
        public static string ColSede {
            get {
                return ResourceManager.GetString("ColSede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        public static string ColServicio {
            get {
                return ResourceManager.GetString("ColServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicios.
        /// </summary>
        public static string ColServicios {
            get {
                return ResourceManager.GetString("ColServicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Serv..
        /// </summary>
        public static string ColServiciosCorto {
            get {
                return ResourceManager.GetString("ColServiciosCorto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string ColTelefono {
            get {
                return ResourceManager.GetString("ColTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string ColTipo {
            get {
                return ResourceManager.GetString("ColTipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Curso.
        /// </summary>
        public static string ColTipoCurso {
            get {
                return ResourceManager.GetString("ColTipoCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        public static string ColTitulo {
            get {
                return ResourceManager.GetString("ColTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad Cuotas.
        /// </summary>
        public static string ColTotalCuota {
            get {
                return ResourceManager.GetString("ColTotalCuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zona Geográfica.
        /// </summary>
        public static string ColZona {
            get {
                return ResourceManager.GetString("ColZona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Email &apos;{0}&apos; ya esta en uso.
        /// </summary>
        public static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Tipo y Nro de Documento ingresados ya estan en uso.
        /// </summary>
        public static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bienvenido a la pagina.
        /// </summary>
        public static string emailBienvenida {
            get {
                return ResourceManager.GetString("emailBienvenida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ingresar el Nombre.
        /// </summary>
        public static string ErrorCampoNombre {
            get {
                return ResourceManager.GetString("ErrorCampoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a * Este campo es obligatorio.
        /// </summary>
        public static string ErrorCampoObligatorio {
            get {
                return ResourceManager.GetString("ErrorCampoObligatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe estar entre 0 y 100.
        /// </summary>
        public static string ErrorCampoOrden {
            get {
                return ResourceManager.GetString("ErrorCampoOrden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imposible eliminar el registro por conflicto de Reglas de Integridad de Datos.
        /// </summary>
        public static string ErrorEliminarRegistroPorIntegridad {
            get {
                return ResourceManager.GetString("ErrorEliminarRegistroPorIntegridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar editar el registro: {0}.
        /// </summary>
        public static string ErrorIntentarEditarRegistro {
            get {
                return ResourceManager.GetString("ErrorIntentarEditarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar insertar el registro: {0}.
        /// </summary>
        public static string ErrorIntentarInsertarRegistro {
            get {
                return ResourceManager.GetString("ErrorIntentarInsertarRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Han ocurrido algunos errores, por favor, revisa el formulario.
        /// </summary>
        public static string ErrorMensajeGenerico {
            get {
                return ResourceManager.GetString("ErrorMensajeGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Felicidades, usted puede gozar de beneficios por ser mayor de 60 años, para esto debe presentarse en la oficina de socioculturales.
        /// </summary>
        public static string MensajeMayor60 {
            get {
                return ResourceManager.GetString("MensajeMayor60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Redes.
        /// </summary>
        public static string MenuRedesEstado {
            get {
                return ResourceManager.GetString("MenuRedesEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar registro.
        /// </summary>
        public static string MsgBorrar {
            get {
                return ResourceManager.GetString("MsgBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columnas.
        /// </summary>
        public static string MsgColumnas {
            get {
                return ResourceManager.GetString("MsgColumnas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea borrar este registro?.
        /// </summary>
        public static string MsgDeseaBorrar {
            get {
                return ResourceManager.GetString("MsgDeseaBorrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar registro.
        /// </summary>
        public static string MsgEditar {
            get {
                return ResourceManager.GetString("MsgEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jurisdicción.
        /// </summary>
        public static string MsgJurisdiccion {
            get {
                return ResourceManager.GetString("MsgJurisdiccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo registro.
        /// </summary>
        public static string MsgNuevo {
            get {
                return ResourceManager.GetString("MsgNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuración.
        /// </summary>
        public static string MsgOpciones {
            get {
                return ResourceManager.GetString("MsgOpciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros Criterios de Búsqueda.
        /// </summary>
        public static string MsgOtrosFiltros {
            get {
                return ResourceManager.GetString("MsgOtrosFiltros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Red.
        /// </summary>
        public static string MsgRed {
            get {
                return ResourceManager.GetString("MsgRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Niveles de Complejidad).
        /// </summary>
        public static string MsgTodasComplejidades {
            get {
                return ResourceManager.GetString("MsgTodasComplejidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todas las Jurisdicciones).
        /// </summary>
        public static string MsgTodasJurisdicciones {
            get {
                return ResourceManager.GetString("MsgTodasJurisdicciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todas las Plantillas de Email).
        /// </summary>
        public static string MsgTodasLasPlantillas {
            get {
                return ResourceManager.GetString("MsgTodasLasPlantillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todas las Redes).
        /// </summary>
        public static string MsgTodasRedes {
            get {
                return ResourceManager.GetString("MsgTodasRedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todas las Regiones).
        /// </summary>
        public static string MsgTodasRegiones {
            get {
                return ResourceManager.GetString("MsgTodasRegiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todas las Sedes).
        /// </summary>
        public static string MsgTodasSedes {
            get {
                return ResourceManager.GetString("MsgTodasSedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todas las Zonas).
        /// </summary>
        public static string MsgTodasZonas {
            get {
                return ResourceManager.GetString("MsgTodasZonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Alumnos).
        /// </summary>
        public static string MsgTodosAlumnos {
            get {
                return ResourceManager.GetString("MsgTodosAlumnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Campos).
        /// </summary>
        public static string MsgTodosCampos {
            get {
                return ResourceManager.GetString("MsgTodosCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Diagnósticos).
        /// </summary>
        public static string MsgTodosDiagnosticos {
            get {
                return ResourceManager.GetString("MsgTodosDiagnosticos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Docentes).
        /// </summary>
        public static string MsgTodosDocentes {
            get {
                return ResourceManager.GetString("MsgTodosDocentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Estados).
        /// </summary>
        public static string MsgTodosEstados {
            get {
                return ResourceManager.GetString("MsgTodosEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Institutos).
        /// </summary>
        public static string MsgTodosInstitutos {
            get {
                return ResourceManager.GetString("MsgTodosInstitutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos las Ofertas).
        /// </summary>
        public static string MsgTodosLasOfertas {
            get {
                return ResourceManager.GetString("MsgTodosLasOfertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Conceptos).
        /// </summary>
        public static string MsgTodosLosConceptos {
            get {
                return ResourceManager.GetString("MsgTodosLosConceptos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Cursos).
        /// </summary>
        public static string MsgTodosLosCursos {
            get {
                return ResourceManager.GetString("MsgTodosLosCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todas los Días).
        /// </summary>
        public static string MsgTodosLosDias {
            get {
                return ResourceManager.GetString("MsgTodosLosDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Periodos).
        /// </summary>
        public static string MsgTodosLosPeriodos {
            get {
                return ResourceManager.GetString("MsgTodosLosPeriodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Roles).
        /// </summary>
        public static string MsgTodosRoles {
            get {
                return ResourceManager.GetString("MsgTodosRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Tipos).
        /// </summary>
        public static string MsgTodosTipos {
            get {
                return ResourceManager.GetString("MsgTodosTipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Todos los Tipos de Curso).
        /// </summary>
        public static string MsgTodosTiposCurso {
            get {
                return ResourceManager.GetString("MsgTodosTiposCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver más .
        /// </summary>
        public static string MsgVerMas {
            get {
                return ResourceManager.GetString("MsgVerMas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N/D.
        /// </summary>
        public static string Nivel0 {
            get {
                return ResourceManager.GetString("Nivel0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a I.
        /// </summary>
        public static string Nivel1 {
            get {
                return ResourceManager.GetString("Nivel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a II.
        /// </summary>
        public static string Nivel2 {
            get {
                return ResourceManager.GetString("Nivel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a III.
        /// </summary>
        public static string Nivel3 {
            get {
                return ResourceManager.GetString("Nivel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IV.
        /// </summary>
        public static string Nivel4 {
            get {
                return ResourceManager.GetString("Nivel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Curso Correlativo).
        /// </summary>
        public static string SeleccionarCorrelativa {
            get {
                return ResourceManager.GetString("SeleccionarCorrelativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Curso).
        /// </summary>
        public static string SeleccionarCurso {
            get {
                return ResourceManager.GetString("SeleccionarCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione un Día).
        /// </summary>
        public static string SeleccionarDia {
            get {
                return ResourceManager.GetString("SeleccionarDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Docente).
        /// </summary>
        public static string SeleccionarDocente {
            get {
                return ResourceManager.GetString("SeleccionarDocente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Estado actual).
        /// </summary>
        public static string SeleccionarEstado {
            get {
                return ResourceManager.GetString("SeleccionarEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione la Jurisdicción).
        /// </summary>
        public static string SeleccionarJurisdiccion {
            get {
                return ResourceManager.GetString("SeleccionarJurisdiccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione un Localidad).
        /// </summary>
        public static string SeleccionarLocalidad {
            get {
                return ResourceManager.GetString("SeleccionarLocalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el motivo).
        /// </summary>
        public static string SeleccionarMotivoBaja {
            get {
                return ResourceManager.GetString("SeleccionarMotivoBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Nivel de Complejidad).
        /// </summary>
        public static string SeleccionarNivel {
            get {
                return ResourceManager.GetString("SeleccionarNivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione la Oferta).
        /// </summary>
        public static string SeleccionarOferta {
            get {
                return ResourceManager.GetString("SeleccionarOferta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Periodo Lectivo).
        /// </summary>
        public static string SeleccionarPeriodoLectivo {
            get {
                return ResourceManager.GetString("SeleccionarPeriodoLectivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione la Plantilla de Email).
        /// </summary>
        public static string SeleccionarPlantilla {
            get {
                return ResourceManager.GetString("SeleccionarPlantilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione un Provincia).
        /// </summary>
        public static string SeleccionarProvincia {
            get {
                return ResourceManager.GetString("SeleccionarProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione la Red).
        /// </summary>
        public static string SeleccionarRed {
            get {
                return ResourceManager.GetString("SeleccionarRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione la Región).
        /// </summary>
        public static string SeleccionarRegion {
            get {
                return ResourceManager.GetString("SeleccionarRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione primero la Jurisdicción).
        /// </summary>
        public static string SeleccionarRegionInicio {
            get {
                return ResourceManager.GetString("SeleccionarRegionInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione una Sede).
        /// </summary>
        public static string SeleccionarSede {
            get {
                return ResourceManager.GetString("SeleccionarSede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Tipo de Alumno).
        /// </summary>
        public static string SeleccionarTipoAlumno {
            get {
                return ResourceManager.GetString("SeleccionarTipoAlumno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Tipo de Curso).
        /// </summary>
        public static string SeleccionarTipoCurso {
            get {
                return ResourceManager.GetString("SeleccionarTipoCurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Seleccione el Tipo de Instituto).
        /// </summary>
        public static string SeleccionarTipoInstituto {
            get {
                return ResourceManager.GetString("SeleccionarTipoInstituto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The statement has been terminated..
        /// </summary>
        public static string TheStatementHasBeenTerminated {
            get {
                return ResourceManager.GetString("TheStatementHasBeenTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        public static string TituloAdmin {
            get {
                return ResourceManager.GetString("TituloAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos de Acción.
        /// </summary>
        public static string TituloCampos {
            get {
                return ResourceManager.GetString("TituloCampos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comunicaciones.
        /// </summary>
        public static string TituloComunicaciones {
            get {
                return ResourceManager.GetString("TituloComunicaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correlativas.
        /// </summary>
        public static string TituloCorrelativas {
            get {
                return ResourceManager.GetString("TituloCorrelativas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuotas.
        /// </summary>
        public static string TituloCuotas {
            get {
                return ResourceManager.GetString("TituloCuotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cursos.
        /// </summary>
        public static string TituloCursos {
            get {
                return ResourceManager.GetString("TituloCursos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Días.
        /// </summary>
        public static string TituloDias {
            get {
                return ResourceManager.GetString("TituloDias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documentos.
        /// </summary>
        public static string TituloDocumentos {
            get {
                return ResourceManager.GetString("TituloDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CNRL Centro Nacional de Redes de Laboratorios.
        /// </summary>
        public static string TituloHome {
            get {
                return ResourceManager.GetString("TituloHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string TituloInicio {
            get {
                return ResourceManager.GetString("TituloInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Jurisdiccionales.
        /// </summary>
        public static string TituloJurisdicciones {
            get {
                return ResourceManager.GetString("TituloJurisdicciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a menú Principal.
        /// </summary>
        public static string TituloMenuPpal {
            get {
                return ResourceManager.GetString("TituloMenuPpal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nodos en Red.
        /// </summary>
        public static string TituloNodos {
            get {
                return ResourceManager.GetString("TituloNodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ofertas.
        /// </summary>
        public static string TituloOfertas {
            get {
                return ResourceManager.GetString("TituloOfertas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendientes.
        /// </summary>
        public static string TituloPendientes {
            get {
                return ResourceManager.GetString("TituloPendientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas.
        /// </summary>
        public static string TituloPersonas {
            get {
                return ResourceManager.GetString("TituloPersonas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de Redes.
        /// </summary>
        public static string TituloRedesEstado {
            get {
                return ResourceManager.GetString("TituloRedesEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Locales.
        /// </summary>
        public static string TituloRedesJur {
            get {
                return ResourceManager.GetString("TituloRedesJur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Jurisdiccionales Locales.
        /// </summary>
        public static string TituloRedesJurLargo {
            get {
                return ResourceManager.GetString("TituloRedesJurLargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Nacionales.
        /// </summary>
        public static string TituloRedesNac {
            get {
                return ResourceManager.GetString("TituloRedesNac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redes Nacionales y Locales.
        /// </summary>
        public static string TituloRedesNacJur {
            get {
                return ResourceManager.GetString("TituloRedesNacJur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Región Sanitaria.
        /// </summary>
        public static string TituloRegion {
            get {
                return ResourceManager.GetString("TituloRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regiones Sanitarias.
        /// </summary>
        public static string TituloRegiones {
            get {
                return ResourceManager.GetString("TituloRegiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sedes.
        /// </summary>
        public static string TituloSedes {
            get {
                return ResourceManager.GetString("TituloSedes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipos de Instituto.
        /// </summary>
        public static string TituloTipos {
            get {
                return ResourceManager.GetString("TituloTipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string TituloUsuarios {
            get {
                return ResourceManager.GetString("TituloUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zonas Geográficas.
        /// </summary>
        public static string TituloZonas {
            get {
                return ResourceManager.GetString("TituloZonas", resourceCulture);
            }
        }
    }
}
