//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnrl
{
    using System;
    using System.Collections.Generic;
    
    public partial class XX_usuarios
    {
        public string nroDoc { get; set; }
        public string clave { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string calle { get; set; }
        public Nullable<int> nroCalle { get; set; }
        public Nullable<System.DateTime> fechaNac { get; set; }
        public string telefono { get; set; }
        public Nullable<int> tipoUsuario { get; set; }
        public Nullable<int> tipoDoc { get; set; }
        public string email { get; set; }
        public string keyToken { get; set; }
        public string telefono2 { get; set; }
        public string piso { get; set; }
        public string depto { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public long codigo { get; set; }
        public Nullable<long> documento { get; set; }
        public Nullable<int> codLocaldiad { get; set; }
        public Nullable<int> codProvincia { get; set; }
        public string ape { get; set; }
    }
}
